root: ../data/exp/RHCR/
max_workers: 26
time_limit_sec: 14400 # 4 hours

n_seeds: 10
simulation_time: 5000

scenarios:
  - MT
solvers:
  - PBS
  - LaCAM
maps:
  - fulfillment_large_empty.map
  - fulfillmenet_large.map
num_agents:
  - 1
  - 10
  - 100
  - 200
  - 300
  - 400
  - 500
  - 1000
  - 2000
  - 3000
  - 4000
  - 5000
simulation_windows:
  - 10
  - 100
  - 200
  - 500
  - 1000
