root: ../data/exp/RHCR/
max_workers: 8
time_limit_sec: 7200

scenarios:
  - MT
solvers:
  - PBS
  - LaCAM
maps:
  - fulfillment_large_empty.map
num_agents:
  - 10
  - 100
  - 1000
  - 2000
  # - 5000
simulation_windows:
  - 100
planning_windows:
  - 200
seeds:
  - 0
  - 1
  - 2
  - 3
  - 4
simulation_time: 5000
