root: ../data/exp/RHCR/
max_workers: 20
time_limit_sec: 7200 # 2 hours

n_seeds: 10
simulation_time: 5000

maps:
  - fulfillment_large_empty.map
  - fulfillment_large.map
simulation_windows:
  - 10
  - 100
  - 200
  - 500
  - 1000
solvers:
  PBS:
    num_agents:
      - 1
      - 10
      - 100
      - 200
      - 300
      - 400
      - 500
  LaCAM:
    num_agents:
      - 1
      - 10
      - 100
      - 200
      - 300
      - 400
      - 500
      - 1000
      - 2000
      - 3000
      - 4000
      - 5000
