root: ../data/exp/RHCR/
max_workers: 8
time_limit_sec: 14400 # 4 hours

scenarios:
  - MT
solvers:
  - PBS
  - LaCAM
maps:
  - fulfillment_large_empty.map
num_agents:
  - 10
  - 100
  - 500
  - 1000
  - 2000
  - 3000
  - 4000
  - 5000
simulation_windows:
  - 10
  - 100
  - 200
  - 500
seeds:
  - 0
  - 1
  - 2
  - 3
  - 4
simulation_time: 5000
